from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Sequence

import mlflow
import yaml
from databricks.sdk import WorkspaceClient
from databricks.sdk.service.catalog import PermissionsChange, Privilege, SecurableType
from mlflow.entities.trace_location import UnityCatalog

from .release import AgentRelease, AgentReleaseLoader, load_release


APP_NAME_RE = re.compile(r"^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$")
MAX_APP_NAME_LENGTH = 26
GENERATED_MARKER = ".aops-generated"
TRACE_TABLE_SUFFIXES = (
    "otel_annotations",
    "otel_logs",
    "otel_metrics",
    "otel_spans",
)


class DeployError(RuntimeError):
    pass


@dataclass(frozen=True)
class AppBuild:
    root: Path
    app_name: str
    agent_id: str
    release_version: str
    model_endpoint: str
    experiment_name: str
    experiment_id: str
    trace_catalog: str
    trace_schema: str


@dataclass(frozen=True)
class DeploymentResult:
    build: AppBuild
    app_url: str | None

    @property
    def mcp_url(self) -> str | None:
        return f"{self.app_url.rstrip('/')}/mcp" if self.app_url else None


CommandRunner = Callable[[Sequence[str], Path], subprocess.CompletedProcess[str]]
ExperimentResolver = Callable[[str, str, str, str, str], str]


def default_app_name(agent_id: str) -> str:
    candidate = f"mcp-{agent_id}"
    if len(candidate) <= MAX_APP_NAME_LENGTH:
        return candidate
    raise DeployError(
        f"기본 App 이름이 {MAX_APP_NAME_LENGTH}자를 초과합니다: {candidate}; "
        "--app-name으로 더 짧은 이름을 지정하세요."
    )


def validate_app_name(value: str) -> str:
    name = value.strip()
    if not APP_NAME_RE.fullmatch(name) or len(name) > MAX_APP_NAME_LENGTH:
        raise DeployError(
            "App 이름은 소문자로 시작하는 kebab-case이며 26자 이하여야 합니다."
        )
    if not name.startswith("mcp-"):
        raise DeployError("MCP App 이름은 Databricks 검색을 위해 'mcp-'로 시작해야 합니다.")
    return name


def infer_trace_schema(release: AgentRelease) -> tuple[str, str]:
    locations = {skill.uc_parts[:2] for skill in release.skills}
    if len(locations) != 1:
        raise DeployError(
            "UC Skills가 여러 catalog/schema에 걸쳐 있습니다. "
            "--trace-schema <catalog.schema>를 명시하세요."
        )
    return next(iter(locations))


def parse_trace_schema(value: str) -> tuple[str, str]:
    parts = value.split(".")
    if len(parts) != 2 or any(not part.strip() or any(ch.isspace() for ch in part) for part in parts):
        raise DeployError("Trace schema는 <catalog>.<schema> 형식이어야 합니다.")
    return parts[0], parts[1]


class McpAppBuilder:
    def build(
        self,
        *,
        release: AgentRelease,
        runtime_root: str | Path,
        output: str | Path,
        app_name: str,
        model_endpoint: str,
        experiment_name: str,
        experiment_id: str,
        trace_catalog: str,
        trace_schema: str,
        warehouse_id: str,
    ) -> AppBuild:
        app_name = validate_app_name(app_name)
        runtime = Path(runtime_root).expanduser().resolve()
        if not (runtime / "config.yaml").is_file():
            raise DeployError(f"검증된 Agent Runtime이 아닙니다: {runtime}")
        target = Path(output).expanduser().resolve()
        target.parent.mkdir(parents=True, exist_ok=True)

        if target.exists() and not (target / GENERATED_MARKER).is_file():
            raise DeployError(f"생성 도구가 관리하지 않는 경로는 덮어쓰지 않습니다: {target}")

        template = Path(__file__).parent / "templates" / "mcp_app"
        with tempfile.TemporaryDirectory(prefix="aops-app-", dir=target.parent) as temporary:
            staging = Path(temporary) / "app"
            ignored = shutil.ignore_patterns("__pycache__", "*.pyc")
            shutil.copytree(template, staging, ignore=ignored)
            shutil.copytree(runtime, staging / "runtime", ignore=ignored)
            # Preserve the local bundle binding/state across deterministic rebuilds.
            # It is never uploaded as App source (see sync.exclude below).
            bundle_state = target / ".databricks"
            if bundle_state.is_dir():
                shutil.copytree(bundle_state, staging / ".databricks", ignore=ignored)
            (staging / GENERATED_MARKER).write_text(
                "Generated by aops deploy. Do not edit; rebuild from the Agent release.\n",
                encoding="utf-8",
            )

            app_config = {
                "command": ["python", "-m", "server.main"],
                "env": [
                    {
                        "name": "DATABRICKS_SERVING_ENDPOINT_NAME",
                        "valueFrom": "serving-endpoint",
                    },
                    {"name": "MLFLOW_EXPERIMENT_ID", "valueFrom": "experiment"},
                    {"name": "MLFLOW_TRACKING_URI", "value": "databricks"},
                    {
                        "name": "MLFLOW_TRACING_SQL_WAREHOUSE_ID",
                        "value": warehouse_id,
                    },
                    {"name": "AOPS_AGENT_ID", "value": release.agent_id},
                    {"name": "AOPS_RELEASE_VERSION", "value": release.release_version},
                ],
            }
            (staging / "app.yaml").write_text(
                yaml.safe_dump(app_config, allow_unicode=True, sort_keys=False),
                encoding="utf-8",
            )

            bundle = {
                "bundle": {"name": app_name},
                # The generated directory lives below an ignored .aops path. Include only
                # runtime source and exclude local bundle state and Python cache files.
                "sync": {
                    "include": [
                        "app.yaml",
                        "requirements.txt",
                        "README.md",
                        "deployment.yaml",
                        "server/**",
                        "runtime/**",
                    ]
                },
                "resources": {
                    "apps": {
                        "agent_mcp": {
                            "name": app_name,
                            "description": (
                                f"Harness Agent MCP: {release.agent_id}@{release.release_version}"
                            ),
                            "source_code_path": ".",
                            "lifecycle": {"started": True},
                            "user_api_scopes": ["serving.serving-endpoints"],
                            "config": {
                                "command": app_config["command"],
                                "env": [
                                    {
                                        "name": item["name"],
                                        **(
                                            {"value_from": item["valueFrom"]}
                                            if "valueFrom" in item
                                            else {"value": item["value"]}
                                        ),
                                    }
                                    for item in app_config["env"]
                                ],
                            },
                            "resources": [
                                {
                                    "name": "serving-endpoint",
                                    "serving_endpoint": {
                                        "name": model_endpoint,
                                        "permission": "CAN_QUERY",
                                    },
                                },
                                {
                                    "name": "experiment",
                                    "experiment": {
                                        "experiment_id": experiment_id,
                                        "permission": "CAN_MANAGE",
                                    },
                                },
                            ],
                        }
                    }
                },
                "targets": {"default": {"default": True}},
            }
            (staging / "databricks.yml").write_text(
                yaml.safe_dump(bundle, allow_unicode=True, sort_keys=False),
                encoding="utf-8",
            )

            deployment = {
                "schema_version": 1,
                "agent_id": release.agent_id,
                "release_version": release.release_version,
                "app_name": app_name,
                "model_endpoint": model_endpoint,
                "experiment_name": experiment_name,
                "experiment_id": experiment_id,
                "trace_location": {
                    "catalog": trace_catalog,
                    "schema": trace_schema,
                },
                "authentication": "oauth-obo",
                "mcp_path": "/mcp",
            }
            (staging / "deployment.yaml").write_text(
                yaml.safe_dump(deployment, allow_unicode=True, sort_keys=False),
                encoding="utf-8",
            )

            if target.exists():
                shutil.rmtree(target)
            shutil.move(str(staging), str(target))

        return AppBuild(
            root=target,
            app_name=app_name,
            agent_id=release.agent_id,
            release_version=release.release_version,
            model_endpoint=model_endpoint,
            experiment_name=experiment_name,
            experiment_id=experiment_id,
            trace_catalog=trace_catalog,
            trace_schema=trace_schema,
        )


class DatabricksAppDeployer:
    def __init__(
        self,
        profile: str,
        *,
        workspace: WorkspaceClient | None = None,
        runner: CommandRunner | None = None,
        experiment_resolver: ExperimentResolver | None = None,
    ) -> None:
        if not profile.strip():
            raise DeployError("Databricks profile is required.")
        self.profile = profile
        self.workspace = workspace or WorkspaceClient(profile=profile)
        self.runner = runner or _run_command
        self.experiment_resolver = experiment_resolver or ensure_uc_trace_experiment

    def deploy(
        self,
        root: str | Path,
        *,
        model_endpoint: str,
        experiment_name: str | None = None,
        trace_schema: str | None = None,
        warehouse_id: str,
        app_name: str | None = None,
        output: str | Path | None = None,
        build_only: bool = False,
    ) -> DeploymentResult:
        release = load_release(root)
        resolved_app_name = validate_app_name(app_name or default_app_name(release.agent_id))
        resolved_experiment = experiment_name or f"/Shared/agentops/{release.agent_id}"
        if not resolved_experiment.startswith("/"):
            raise DeployError("MLflow Experiment는 /Shared/... 또는 /Users/... 절대 경로여야 합니다.")
        catalog, schema = (
            parse_trace_schema(trace_schema)
            if trace_schema
            else infer_trace_schema(release)
        )
        self._validate_endpoint(model_endpoint)
        self._ensure_experiment_parent(resolved_experiment)
        experiment_id = self.experiment_resolver(
            self.profile,
            resolved_experiment,
            catalog,
            schema,
            warehouse_id,
        )

        agent_root = Path(root).expanduser().resolve()
        build_root = Path(output or agent_root / ".aops" / "apps" / resolved_app_name)
        build_root.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(prefix="aops-deploy-", dir=build_root.parent) as temporary:
            runtime = Path(temporary) / "runtime"
            AgentReleaseLoader(self.profile).assemble(agent_root, destination=runtime)
            build = McpAppBuilder().build(
                release=release,
                runtime_root=runtime,
                output=build_root,
                app_name=resolved_app_name,
                model_endpoint=model_endpoint,
                experiment_name=resolved_experiment,
                experiment_id=experiment_id,
                trace_catalog=catalog,
                trace_schema=schema,
                warehouse_id=warehouse_id,
            )

        if build_only:
            return DeploymentResult(build=build, app_url=None)

        self._checked(
            ["databricks", "bundle", "validate", "--target", "default", "--profile", self.profile],
            build.root,
            "validate Databricks App",
        )
        self._checked(
            [
                "databricks",
                "bundle",
                "deploy",
                "--target",
                "default",
                "--auto-approve",
                "--profile",
                self.profile,
            ],
            build.root,
            "deploy Databricks App",
        )
        self._grant_trace_permissions(
            resolved_app_name,
            catalog=catalog,
            schema=schema,
            experiment_id=experiment_id,
        )
        self._checked(
            ["databricks", "apps", "start", resolved_app_name, "--profile", self.profile],
            build.root,
            "start Databricks App",
        )
        app_url = self._app_url(resolved_app_name, build.root)
        return DeploymentResult(build=build, app_url=app_url)

    def _grant_trace_permissions(
        self,
        app_name: str,
        *,
        catalog: str,
        schema: str,
        experiment_id: str,
    ) -> None:
        try:
            app = self.workspace.apps.get(app_name)
            principal = str(getattr(app, "service_principal_client_id", "") or "")
            if not principal:
                raise DeployError(f"App Service Principal을 확인할 수 없습니다: {app_name}")
            self.workspace.grants.update(
                SecurableType.CATALOG.value,
                catalog,
                changes=[
                    PermissionsChange(principal=principal, add=[Privilege.USE_CATALOG])
                ],
            )
            self.workspace.grants.update(
                SecurableType.SCHEMA.value,
                f"{catalog}.{schema}",
                changes=[
                    PermissionsChange(principal=principal, add=[Privilege.USE_SCHEMA])
                ],
            )
            for suffix in TRACE_TABLE_SUFFIXES:
                self.workspace.grants.update(
                    SecurableType.TABLE.value,
                    f"{catalog}.{schema}.{experiment_id}_{suffix}",
                    changes=[
                        PermissionsChange(
                            principal=principal,
                            add=[Privilege.SELECT, Privilege.MODIFY],
                        )
                    ],
                )
        except DeployError:
            raise
        except Exception as exc:
            raise DeployError(f"App에 UC Trace 최소 권한을 부여할 수 없습니다: {exc}") from exc

    def _validate_endpoint(self, name: str) -> None:
        try:
            endpoint = self.workspace.serving_endpoints.get(name)
        except Exception as exc:
            raise DeployError(f"Model Serving endpoint를 확인할 수 없습니다: {name}: {exc}") from exc
        ready = getattr(getattr(endpoint, "state", None), "ready", None)
        ready_value = str(getattr(ready, "value", ready) or "")
        if ready_value and ready_value != "READY":
            raise DeployError(f"Model Serving endpoint가 READY 상태가 아닙니다: {name} ({ready_value})")

    def _ensure_experiment_parent(self, experiment_name: str) -> None:
        parent = str(Path(experiment_name).parent)
        if parent in {".", "/"}:
            return
        try:
            self.workspace.workspace.mkdirs(parent)
        except Exception as exc:
            raise DeployError(f"MLflow Experiment 상위 경로를 만들 수 없습니다: {parent}: {exc}") from exc

    def _app_url(self, app_name: str, cwd: Path) -> str | None:
        result = self.runner(
            ["databricks", "apps", "get", app_name, "--profile", self.profile, "-o", "json"],
            cwd,
        )
        if result.returncode != 0:
            return None
        try:
            value = json.loads(result.stdout).get("url")
        except (json.JSONDecodeError, AttributeError):
            return None
        return str(value).rstrip("/") if value else None

    def _checked(self, command: Sequence[str], cwd: Path, action: str) -> None:
        result = self.runner(command, cwd)
        if result.returncode != 0:
            message = (result.stderr or result.stdout or f"exit code {result.returncode}").strip()
            raise DeployError(f"Cannot {action}: {message}")


def ensure_uc_trace_experiment(
    profile: str,
    experiment_name: str,
    catalog: str,
    schema: str,
    warehouse_id: str,
) -> str:
    previous_uri = mlflow.get_tracking_uri()
    previous_warehouse = os.environ.get("MLFLOW_TRACING_SQL_WAREHOUSE_ID")
    previous_profile = os.environ.get("DATABRICKS_CONFIG_PROFILE")
    try:
        # UC trace provisioning creates both MLflow and SQL clients internally.
        # Set the profile for both so neither client can fall back to DEFAULT.
        os.environ["DATABRICKS_CONFIG_PROFILE"] = profile
        mlflow.set_tracking_uri(f"databricks://{profile}")
        os.environ["MLFLOW_TRACING_SQL_WAREHOUSE_ID"] = warehouse_id
        desired = UnityCatalog(catalog_name=catalog, schema_name=schema)
        experiment = mlflow.get_experiment_by_name(experiment_name)
        if experiment is None:
            return str(mlflow.create_experiment(experiment_name, trace_location=desired))

        current = getattr(experiment, "trace_location", None)
        if current is None:
            experiment = mlflow.set_experiment(
                experiment_name=experiment_name,
                trace_location=desired,
            )
            return str(experiment.experiment_id)

        current_catalog = getattr(current, "catalog_name", None)
        current_schema = getattr(current, "schema_name", None)
        if (current_catalog, current_schema) != (catalog, schema):
            raise DeployError(
                f"Experiment의 기존 UC Trace 위치가 다릅니다: "
                f"{current_catalog}.{current_schema} (요청: {catalog}.{schema})"
            )
        return str(experiment.experiment_id)
    except DeployError:
        raise
    except Exception as exc:
        raise DeployError(f"UC Trace Experiment를 준비할 수 없습니다: {exc}") from exc
    finally:
        mlflow.set_tracking_uri(previous_uri)
        if previous_warehouse is None:
            os.environ.pop("MLFLOW_TRACING_SQL_WAREHOUSE_ID", None)
        else:
            os.environ["MLFLOW_TRACING_SQL_WAREHOUSE_ID"] = previous_warehouse
        if previous_profile is None:
            os.environ.pop("DATABRICKS_CONFIG_PROFILE", None)
        else:
            os.environ["DATABRICKS_CONFIG_PROFILE"] = previous_profile


def _run_command(command: Sequence[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(list(command), cwd=cwd, capture_output=True, text=True, check=False)
